spring:
  application:
    name: gateway-service
  redis:
    host: localhost
    port: 6379
    database: 0
    # 如果redis有密码则加上
  # password: imooc
  cloud:
    gateway:
      # 跨域配置
      globalcors:
        cors-configurations:
          '[/**]':
            # 此处可添加多个授信的地址
            allowed-origins:
              - "http://localhost:8080"
              - "*"
            # 比如cookie, authorization之类的认证信息
            allow-credentials: true
            allowed-headers: "*"
            allowed-methods: "*"
            expose-headers: "*"
            # 表示Options可以在浏览器缓存多长时间
            max-age: 1000
      locator:
        enabled: false
        lower-case-service-id: true

server:
  port: 10005

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/

## 开启所有actuator-endpoint
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false