apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      restartPolicy: Always
      containers:
      - name: config-server
        image: config-server
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 200Mi
            cpu: 200m
          limits:
            memory: 1000Mi
            cpu: 500m
        livenessProbe: 
          httpGet:
            path: /actuator/health
            port: 10004 
          initialDelaySeconds: 120 
          periodSeconds: 60
          timeoutSeconds: 10
