apiVersion: apps/v1
kind: Deployment
metadata:
  name: coupon-template
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coupon-template
  template:
    metadata:
      labels:
        app: coupon-template
    spec:
      restartPolicy: Always
      containers:
      - name: coupon-template
        image: coupon-template
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 200Mi
            cpu: 200m
          limits:
            memory: 1000Mi
            cpu: 500m
        livenessProbe: 
          httpGet:
            path: /actuator/health
            port: 20000
          initialDelaySeconds: 120 
          periodSeconds: 60
          timeoutSeconds: 10
