apiVersion: v1
kind: Service
metadata:
  name: eureka-nodeport
spec:
  type: NodePort
  selector:
    app: eureka
  ports:
  - protocol: TCP
    port: 10000
    targetPort: 10000
    nodePort: 30000

