server:
  port: 20001
#  servlet:
#    context-path: /coupon-calculation

spring:
  application:
    name: coupon-calculator-service
  sleuth:
    sampler:
      probability: 1
  zipkin:
    sender:
      type: rabbit
    rabbitmq:
      addresses: 127.0.0.1:5672
      queue: zipkin

eureka:
  client:
    service-url:
      defaultZone: http://peer1:10000/eureka/,http://peer2:10001/eureka/
