server:
  port: 20000

eureka:
  client:
    service-url:
      # eureka的注册地址
      defaultZone: http://peer1:10000/eureka/,http://peer2:10001/eureka/

spring:
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    # 默认的服务注册名称
    name: coupon-template-service
  datasource:
    # mysql数据源
    username: root
    password: Broadview
    url: jdbc:mysql://127.0.0.1:3306/broadview_coupon_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池
    hikari:
      connection-timeout: 20000
      idle-timeout: 20000
      maximum-pool-size: 20
      minimum-idle: 5
      max-lifetime: 30000
      auto-commit: true
      pool-name: BroadviewCouponHikari
  jpa:
    show-sql: true
    hibernate:
      # 在生产环境全部为none，防止ddl结构被自动执行
      ddl-auto: none
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: true
    open-in-view: false
  sleuth:
    sampler:
      probability: 1
  zipkin:
    sender:
      type: rabbit
    rabbitmq:
      addresses: 127.0.0.1:5672
      queue: zipkin
  cloud:
    alibaba:
      seata:
        tx-service-group: my-group

logging:
  level:
    com.broadview.coupon: debug

# 开启所有management端点
management:
  endpoints:
    web:
      exposure:
        include: "*"

seata:
  application-id: coupon-calculation-service
  registry:
    type: eureka
    eureka:
      application: seata-server
      service-url: http://localhost:10000/eureka/
      weight: 1
  service:
    vgroup-mapping:
      my-group: seata-server